const translations = {
    en: {
        Home: 'Home',
        About: 'About',
        Contact: 'Contact',
        LogIn: 'Log In',
        LogOut: 'Log Out',
        SearchForRooms: 'Search for rooms:',
        Lexicographic: 'Lexicographic',
        Ascending: 'Ascending',
        Descending: 'Descending',
        All: 'All',
        Floor: 'Floor',
        LakeSide: 'Lake Side',
        DarkSide: 'Dark Side',
        Available: 'Available',
        Booked: 'Booked',
        G239: 'The room of Waifu',
        G433: 'The room of founder',
        G120: 'The Walmart version of KFC',
        G343: 'Dorm of half man, half cow',
        G131: 'The Old Gathering Place',
        G230: 'Black & White',
        LeaveNotes: 'Leave Notes',
        SubmitNotes: 'Submit Notes',
        BookNow: 'Book Now',
        AboutUs: 'About us',
        YourComfortIsOurGain: 'Your comfort is our gain 🤑',
        Message1: 'Welcome to KIU Dormitory Hotel, your premier choice for comfortable and affordable student accommodation. Established on June 8th, 2024, by our visionary founder Lado Turmanidze and co-founder Nita Elene Tabidze, we are committed to providing a home away from home for our residents.',
        Message2: 'Our accommodations are located exclusively in the G building, ensuring a focused and community-oriented living environment. We offer a variety of room options to suit your needs and budget:',
        Message3: 'In addition, if you prefer a scenic view of the lake, our odd-numbered rooms are available for a modest additional fee of 5💲.',
        Message4: 'At KIU Dormitory Hotel, we understand the importance of a comfortable and supportive living space during your academic journey. Our goal is to provide a welcoming and secure environment that fosters both academic success and personal growth.',
        Message5: 'Join our community and experience the perfect blend of convenience, affordability, and comfort. We look forward to welcoming you to your new home at KIU Dormitory Hotel!',
        ContactUs: 'Contact Us',
        Profile: 'Profile',
        ProfileAlert: 'Please log in to access your profile',
        Name: 'Name',
        Username: 'Username',
        Email: 'Email',
        Password: 'Password',
        Message: 'Message',
        Submit: 'Submit',
        LogInWithFacebook: 'Log In with Facebook',
        NoDormsBookedYet: 'No dorms booked yet',
        BookedDorms: 'Booked Dorms',
        ReservedFor: 'Reserved for',
        Months: 'months',
        MoreThanAMonth: 'Please select at least one month to book.',
        AlertMessage: 'You need to log in to book a dorm.',
        AlreadyBooked: 'You have already booked this dorm.',
        Phone: 'Phone',
        Website: 'Website',
        SubscribeToNewsletter: 'Subscribe to newsletter',
        Menu: 'Menu'
    },
    ka: {
        Home: 'მთავარი',
        About: 'შესახებ',
        Contact: 'კონტაქტი',
        LogIn: 'შესვლა',
        LogOut: 'გამოსვლა',
        SearchForRooms: 'ოთახების ძიება:',
        Lexicographic: 'ანბაბის მიხედვით',
        Ascending: 'ზრდადობით',
        Descending: 'კლებადობით',
        All: 'ყველა',
        Floor: 'სართული',
        LakeSide: 'ტბის მხარე',
        DarkSide: 'ბნელი მხარე',
        Available: 'ხელმისაწვდომია',
        Booked: 'დაჯავშნილია',
        G239: 'ვაიFუს ოთახი',
        G433: 'დამფუძნებლის ოთახი',
        G120: 'KFC-ის Walmart ვერსია',
        G343: 'ნახევრად კაცის, ნახევრად საქონლის ოთახი',
        G131: 'ძველი თავშეყრის ადგილი',
        G230: 'შავი და თეთრი',
        LeaveNotes: 'დატოვე შენიშვნები',
        SubmitNotes: 'შენიშვნების გაგზავნა',
        BookNow: 'დაჯავშნე ახლა',
        AboutUs: 'Ჩვენს შესახებ',
        YourComfortIsOurGain: 'თქვენი კომფორტი ჩვენი მოგებაა 🤑',
        Message1: 'კეთილი იყოს თქვენი მობრძანება ქუთაისის საერთაშორისო უნივერსიტეტის საერთო საცხოვრებლის სასტუმროებში, თქვენი საუკეთესო არჩევანი კომფორტული და ხელმისაწვდომი სტუდენტური საცხოვრებლისთვის. 2024 წლის 8 ივნისს ჩვენმა დამფუძნებელმა ლადო თურმანიძემ და თანადამფუძნებელმა ნიტა ელენე ტაბიძემ, გადაწყვიტეს, რომ უზრუნველყოთ სახლიდან შორს წამოსული სტუდენტების საცხოვრებლები.',
        Message2: 'ჩვენი საცხოვრებელი განლაგებულია ექსკლუზიურად G კორპუსში, რაც უზრუნველყოფს შედეგზე კონცენტრირებულ და საზოგადოებაზე ორიენტირებულ საცხოვრებელ გარემოს. ჩვენ გთავაზობთ ოთახების მრავალფეროვან არჩევანს თქვენი საჭიროებებისა და ბიუჯეტის შესაბამისად:',
        Message3: 'გარდა ამისა, თუ გირჩევნიათ ტბის ულამაზესი ხედი, კენტ ნომრიან ოთახებს ემატებათ მოკრძალებული დამატებითი საფასური - 5💲.',
        Message4: 'KIU Dormitory Hotel-ში გვესმის კომფორტული და თანამდგომი საცხოვრებელი სივრცის მნიშვნელობა თქვენი აკადემიური მოგზაურობის დროს. ჩვენი მიზანია, უზრუნველვყოთ თბილი და უსაფრთხო გარემო, რომელიც ხელს უწყობს როგორც აკადემიურ წარმატებას, ასევე პიროვნულ ზრდას.',
        Message5: 'შემოუერთდით ჩვენს საზოგადოებას და მიიღეთ ხელსაყრელობის, ხელმისაწვდომობისა და კომფორტის შესანიშნავი ნაზავი. ჩვენ მოუთმენლად ველით თქვენს ახალ სახლში KIU Dormitory Hotel-ში!',
        ContactUs: 'დაგვიკავშირდით',
        Profile: 'პროფილი',
        ProfileAlert: 'გთხოვთ, შედით სისტემაში',
        Name: 'სახელი',
        Username: 'მომხმარებელი',
        Email: 'ელფოსტა',
        Password: 'პაროლი',
        Message: 'შეტყობინება',
        Submit: 'გაგზავნა',
        LogInWithFacebook: 'შედით Facebook-ით',
        NoDormsBookedYet: 'ჯერ არც ერთი ოთახი არ არის დაჯავშნილი',
        BookedDorms: 'დაჯავშნილი დორმები',
        ReservedFor: 'დაჯავნილია',
        Months: 'თვით',
        MoreThanAMonth: 'გთხოვთ, სულ მცირე ერთი თვე მონიშნოთ.',
        AlertMessage: 'დაჯავშნისთვის საჭიროა სისტემაში შესვლა.',
        AlreadyBooked: 'ეს ოთახი უკვე დაჯავშნეთ.',
        Phone: 'ტელეფონი',
        Website: 'ვებგვერდი',
        SubscribeToNewsletter: 'გამოიწერე სიახლეებისათვის',
        Menu: 'მენიუ'
    }
};

export default translations;